version: '3'
services:
  influxdb:
    image: influxdb:latest
    volumes:
      - influxdb_data:/var/lib/influxdb/data
    environment:
      - INFLUXDB_DB=${INFLUXDB_DB:-http://influxdb:8086}
      - INFLUXDB_USER=${INFLUXDB_USER}
      - INFLUXDB_USER_PASSWORD=${INFLUXDB_USER_PASSWORD}
    ports:
      - "8086:8086"

  grafana:
    image: grafana/grafana:latest
    depends_on:
      - influxdb
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${INFLUXDB_USER_PASSWORD}
    ports:
      - "8085:3000"

  nature_remo_collector:
    build:
      context: ./collector
      dockerfile: ./Dockerfile
    depends_on:
      - influxdb
    environment:
      - INFLUXDB_URL=${INFLUXDB_URL:-http://influxdb:8086}
      - INFLUXDB_DB=${INFLUXDB_DB}
      - INFLUXDB_USER=${INFLUXDB_USER}
      - INFLUXDB_USER_PASSWORD=${INFLUXDB_USER_PASSWORD}
      - INFLUXDB_ORG=${INFLUXDB_ORG}
      - INFLUXDB_BUCKET=${INFLUXDB_BUCKET}
      - INFLUXDB_TOKEN=${INFLUXDB_TOKEN}
      - REMO_TOKEN=${REMO_TOKEN}
volumes:
  influxdb_data:
  grafana_data:
